In [1]:
with open('dataset.txt', 'r', encoding='utf-8') as f:
    text = f.read()

In [2]:
print("leght of dataset in characters: ", len(text))

leght of dataset in characters:  172468245


In [4]:
# Let's see the first 1000 characters
print(text[:1000])

Title: प्रार्थना

मेरे पाँव के पास चाँदनी बिछाओ भगवान !
दूज के चाँद पर मुझे खड़ा करो
किसी महाराजा के समान ।
टखने डूबे हों चाँदनी में,

मेरे मोजे मुलायम,चमकदार हों ;
और मेरे मस्तक पर
चाँदनी की झरती फुहार हो ।
शीतलता पर इतराऊँ, चमक पर मचलूँ

चाँदनी में तैरता हुआ मंजिल की ओर चलूँ ।
क्योंकि सूरज काल हो गया है ।
उसका चेहर शेर के समान लाल हो गया है ।
2.  एकान्त

लोग अकेलेपन की शिकायत करते हैं ।
मैं समझ नहीं पाता ,
वे किस बात से डरते हैं ।
अकेलापन तो जीवन का चरम आनन्द है ।

जो हैं निःसंग,
सोचो तो, वही स्वच्छंद है ।
अकेला होने पर जगते हैं विचार;
ऊपर आती है उठकर

अंधकार से नीली झंकार ।
जो है अकेला,
करता है अपना छोटा-मोटा काम,
या लेता हुआ आराम,

झाँक कर देखता है आगे की राह को,
पहुँच से बाहर की दुनिया अथाह को;
तत्वों के केन्द्र-बिन्दु से होकर एकतान
बिना किसी बाधा के करता है ध्यान

विषम के बीच छिपे सम का,
अपने उदगम का ।
3.  अकेलेपन का आनन्द
अकेलेपन से बढ़कर

आनन्द नहीं , आराम नहीं ।
स्वर्ग है वह एकान्त,
जहाँ शोर नहीं, धूमधाम नहीं ।
देश और काल के प्रसार में,

शून्यता, अशब्दता अपार में
चाँद जब घूमता

In [5]:
# All the unique characters in the file
chars = sorted(list(set(text)))
vocab_size = len(chars)
print(''.join(chars))
print('Number of unique characters: ', vocab_size)



 !"'()+,-.0123456789:;=?CTU[]aceilnost|¸ँंःअआइईउऊऋऎएऐओऔकखगघङचछजझञटठडढणतथदधनपफबभमयरलवशषसह़ऽािीुूृॄॅेैॉॊोौ्क़ग़ज़ड़ढ़फ़ॠ।॥०१२३४५६७८९॰‌‍–‘’“”…
Number of unique characters:  134


In [6]:
# create a mapping of unique characters to integers
stoi = {ch: i for i, ch in enumerate(chars)}
itos = {i: ch for i, ch in enumerate(chars)}
encode = lambda s: [stoi[c] for c in s]          # encoder: string -> list of integers
decode = lambda x: ''.join([itos[i] for i in x]) # decoder: list of integers -> string

print(encode('शून्यता'))
print(decode(encode('शून्यता')))

[85, 95, 75, 105, 81, 71, 91]
शून्यता


In [7]:
# Let's encode the whole text
import torch
data = torch.tensor(encode(text), dtype=torch.long)
print(data.size())
print(data[:1000])        # the 1000 first characters, encoded as integers

torch.Size([172468245])
tensor([ 26,  33,  38,  34,  32,  21,   1,  76, 105,  82,  91,  82, 105,  72,
         75,  91,   0,   0,  80,  99,  82,  99,   1,  76,  91,  41,  84,   1,
         56,  99,   1,  76,  91,  87,   1,  61,  91,  41,  73,  75,  93,   1,
         78,  92,  62,  91,  54,   1,  79,  58,  84,  91,  75,   1,   2,   0,
         73,  95,  63,   1,  56,  99,   1,  61,  91,  41,  73,   1,  76,  82,
          1,  80,  94,  64,  99,   1,  57,  68,  89,  91,   1,  56,  82, 103,
          0,  56,  92,  87,  93,   1,  80,  88,  91,  82,  91,  63,  91,   1,
         56,  99,   1,  87,  80,  91,  75,   1, 113,   0,  66,  57,  75,  99,
          1,  68,  95,  78,  99,   1,  88, 103,  42,   1,  61,  91,  41,  73,
         75,  93,   1,  80,  99,  42,   8,   0,   0,  80,  99,  82,  99,   1,
         80, 103,  63,  99,   1,  80,  94,  83,  91,  81,  80,   8,  61,  80,
         56,  73,  91,  82,   1,  88, 103,  42,   1,  22,   0,  55,  82,   1,
         80,  99,  82,  99,   1,  80,  8

In [8]:
# Let's now split the data into training and validation sets
n = int(0.9 * len(data))                        # 90% of the data for training and 10% for validation
train_data, val_data = data[:n], data[n:]

In [15]:
block_size = 8                      # context length
train_data[:block_size+1]
decode(train_data[:block_size+1].tolist())

'Title: प्'

In [21]:
x = train_data[:block_size]
y = train_data[1:block_size+1]
for t in range(block_size):
    context, target = x[:t+1], y[:t]
    # print(f"When input is {decode(context.tolist())}, target is {decode(target.tolist())}")         # uncomment to see the data
    print(f"When input is {context}, target is {target}")
    

When input is tensor([26]), target is tensor([], dtype=torch.int64)
When input is tensor([26, 33]), target is tensor([33])
When input is tensor([26, 33, 38]), target is tensor([33, 38])
When input is tensor([26, 33, 38, 34]), target is tensor([33, 38, 34])
When input is tensor([26, 33, 38, 34, 32]), target is tensor([33, 38, 34, 32])
When input is tensor([26, 33, 38, 34, 32, 21]), target is tensor([33, 38, 34, 32, 21])
When input is tensor([26, 33, 38, 34, 32, 21,  1]), target is tensor([33, 38, 34, 32, 21,  1])
When input is tensor([26, 33, 38, 34, 32, 21,  1, 76]), target is tensor([33, 38, 34, 32, 21,  1, 76])


In [ ]:
torch.manual_seed(1337)
batch_size = 4               # how many independent sequences to train on in parallel                 
block_size = 8               # what is the context length for prediction

def get_batch(split):
    # generate a small batch of data of input x and targets y
    data = train_data if split == 'train' else val_data
    ix = torch.randint(len(data) - block_size, (batch_size,)) # starting index of each sequence
    x = torch.stack([data[i:i+block_size] for i in ix])       # input sequences
    y = torch.stack([data[i+1:i+block_size+1] for i in ix])   # target sequences, i.e. shifted by 1
    return x, y
    
xb, yb = get_batch('train')
print('inputs:')
print(xb.shape)
print(xb)                                                     
# print(decode(xb[0].tolist()))
print('targets:')
print(yb.shape)
print(yb)
# print(decode(yb[0].tolist()))

print('-----------------')

for b in range(batch_size):                                     # iterate over batch dimension
    for t in range(block_size):                                 # iterate over time dimension
        context, target = xb[b, :t+1], yb[b, t]
        print(f"When input is {context.tolist()}, target is {target}")
        # print(f"When input is {decode(context.tolist())}, target is {decode([target.tolist()])}")

inputs:
torch.Size([4, 8])
tensor([[ 91,  82,  91,   1,  85, 103,  70,  92],
        [ 71,  94,  80, 105,  88,  91,  82,  91],
        [ 91,  87,   8,   0,  75,   1,  56,  83],
        [ 84,  75,   8,   1,  84,  92,  76,  92]])
targets:
torch.Size([4, 8])
tensor([[ 82,  91,   1,  85, 103,  70,  92,  71],
        [ 94,  80, 105,  88,  91,  82,  91,   1],
        [ 87,   8,   0,  75,   1,  56,  83,  92],
        [ 75,   8,   1,  84,  92,  76,  92,  75]])
-----------------
When input is [91], target is 82
When input is [91, 82], target is 91
When input is [91, 82, 91], target is 1
When input is [91, 82, 91, 1], target is 85
When input is [91, 82, 91, 1, 85], target is 103
When input is [91, 82, 91, 1, 85, 103], target is 70
When input is [91, 82, 91, 1, 85, 103, 70], target is 92
When input is [91, 82, 91, 1, 85, 103, 70, 92], target is 71
When input is [71], target is 94
When input is [71, 94], target is 80
When input is [71, 94, 80], target is 105
When input is [71, 94, 80, 105], target

In [ ]:
print(xb)          # our input to the transformer

tensor([[ 91,  82,  91,   1,  85, 103,  70,  92],
        [ 71,  94,  80, 105,  88,  91,  82,  91],
        [ 91,  87,   8,   0,  75,   1,  56,  83],
        [ 84,  75,   8,   1,  84,  92,  76,  92]])


In [28]:
import torch
import torch.nn as nn
import torch.nn.functional as F
torch.manual_seed(1337)

class BigramLanguageModel(nn.Module):
    
    def __init__(self, vocab_size):
        super().__init__()
        # each token directly reads off the logits for the next token from a lookup table
        self.token_embedding_table = nn.Embedding(vocab_size, vocab_size)

    def forward(self, idx, targets):
        # idx and targets are both (B, T) Tensor of integers
        logits = self.token_embedding_table(idx)               # (B, T, C)
        return logits
    
m = BigramLanguageModel(vocab_size)
out = m(xb, yb)
print(out.shape) # should be (B, T, C)

torch.Size([4, 8, 134])
